import type { Metadata } from "next";
import { Geist_Mono, Inria_Sans } from "next/font/google";
import "./globals.css";

const inriaSans = Inria_Sans({
  weight: ["300", "400", "700"],
  variable: "--font-inria-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CustomerX - login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/cx-logo.png" />
      </head>
      <body className={`${inriaSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
